// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"

	events "github.com/onflow/flow-go/state/protocol/events"
)

// Views is an autogenerated mock type for the Views type
type Views struct {
	mock.Mock
}

// OnView provides a mock function with given fields: view, callback
func (_m *Views) OnView(view uint64, callback events.OnViewCallback) {
	_m.Called(view, callback)
}
