linters:
  disable-all: true
  enable:
    - govet
    - gosimple
    - errcheck
    - staticcheck
    - structcheck
    - varcheck
    - ineffassign
    - typecheck
    - misspell
    - goimports
    - unused
linters-settings:
  goimports:
    # put imports beginning with prefix after 3rd-party package
    local-prefixes: github.com/onflow/flow-cli
