name: Observer E2E

on:
  push:
    branches:
      - master
      - 'auto-cadence-upgrade/**'
      - staging
      - trying
      - 'feature/**'
      - 'v[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - 'auto-cadence-upgrade/**'
      - 'feature/**'
      - 'v[0-9]+.[0-9]+'

jobs:
  integration-test:
    name: Integration Tests
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.16
          - 1.17
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version}}
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build relic
      run: make crypto_setup_gopath
    - name: Install tools
      run: make install-tools
    - name: Run Observer End To End
      run: bash -c 'cd integration/localnet/ && make -e OBSERVER=1 init && make start && (docker ps | grep observer) && make stop'
  flow-grpc-test:
    name: Client Tests
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.16
          - 1.17
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version}}
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Build relic
      run: make crypto_setup_gopath
    - name: Docker build
      run: make install-tools
    - name: Install Flow Client
      run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)" && mv ~/.local/bin/flow /tmp
    - name: Set up Localnet
      run: bash -c 'cd integration/localnet/ && make -e OBSERVER=1 init && make start'
    - name: Ensure Observer is started
      run: docker ps -q -f name=localnet_observer_1_1
    - name: Wait for finalized blocks and check them with Observer
      run: /tmp/flow -f integration/localnet/flow-localnet.json -n access blocks get latest && /tmp/flow -f integration/localnet/flow-localnet.json -n observer blocks get latest
    - name: Get Version ensuring the official client build can connect
      run: /tmp/flow -f integration/localnet/flow-localnet.json -n observer version
    - name: Get Status ensuring the official client build can connect
      run: /tmp/flow -f integration/localnet/flow-localnet.json -n observer status
    - name: Stop localnet
      run: bash -c 'cd integration/localnet/ && make stop'

